const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const TILE = 28;
const map = [
  '####################', '#........##........#', '#.####.####.####.#.#', '#o####.####.####.#o#', '#..................#', '#.####.##  ##.####.#', '#......#    #......#', '######.#    #.######', '     #.####.#       ', '######.####.######  ', '      .    .        ', '######.####.######  ', '     #.####.#       ', '######.#    #.######', '#......#    #......#', '#.####.##  ##.####.#', '#o... ...........o.#', '####################'
];
const questions = [
  { q:'After completing the V&R checklist for an internal transfer, where must you copy and paste it?', a:['Verint Task 500 case notes','Verint Task 1200 case notes','Verint Task 145 case notes'], correct:0 },
  { q:'What task must be added if the ceding plan value exceeds £50,000?', a:['Task 500 - Internal Transfer Vetting','Task 145 - Box Notifcation with Estimate','Task 505 - Ceding Policy Exit'], correct:1 },
  { q:'Where can you find the required information to complete the Internal Data Capture Form?', a:['Your notes','Verint','General Enquires (GE)'], correct:2 },
  { q:'Where can you find the PSTR number?', a:['Verint','GE','AME'], correct:2 },
  { q:'On your Verint case notes, what should you enter as the subject line for the V&R Checklist?', a:['Transfer Details','V&R Checklist','internal transfer'], correct:1 },
  { q:'What is the correct process for sending an SMS using Esendex?', a:["Log in, select 'Send > Templates', choose the 'V&R Internal Text' template, add the member's mobile number, and send.","Log in, select 'Send > Templates', choose the 'Forms to Member' template, add the member's mobile number, and send.","Log in, select 'Send > Templates', choose the 'V&R External Text' template, add the member's mobile number, and send."], correct:0 },
  { q:'What task should be running when you complete the Internal Transfer Data Capture form, V&R checklist and send an SMS to the member?', a:['Task 1200','Task 500','Task 505'], correct:1 },
  { q:'If the member is completing an internal and external FPJ at the same time, which script needs to be read?', a:['The internal script','Both','The external script'], correct:2 }
];
const ghosts = [{x:9,y:8,color:'#ef6a55',dir:{x:1,y:0}},{x:10,y:8,color:'#46b96b',dir:{x:-1,y:0}},{x:11,y:8,color:'#f5c84b',dir:{x:0,y:-1}},{x:12,y:8,color:'#4169e1',dir:{x:0,y:1}}];
let player, dots, score=0, lives=3, running=false, paused=false, questionIndex=0, lastTime=0, tick=0, winCount=0, questionedGhosts=new Set();
const $ = id => document.getElementById(id);
function moveInterval(){return Math.max(70,125-(winCount*10));}
function resetGame(){ player={x:10,y:16,dir:{x:0,y:0},next:{x:0,y:0}}; dots=[]; map.forEach((row,y)=>[...row].forEach((cell,x)=>{if(cell==='.'||cell==='o') dots.push({x,y,power:cell==='o'});})); ghosts.forEach((g,i)=>Object.assign(g,{x:9+i,y:8,dir:i===1?{x:-1,y:0}:{x:1,y:0} })); score=0;lives=3;questionedGhosts=new Set();updateHud();draw(); }
function isOpen(x,y){ return y>=0&&y<map.length&&x>=0&&x<map[0].length&&map[y][x]!=='#'; }
function move(entity){ const n={x:entity.x+entity.dir.x,y:entity.y+entity.dir.y}; if(isOpen(n.x,n.y)){entity.x=n.x;entity.y=n.y;return true;} return false; }
function updateHud(){ $('score').textContent=String(score).padStart(6,'0');$('lives').textContent=lives;$('dotsLeft').textContent=String(dots.length).padStart(2,'0'); }
function draw(){ ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#0c242f';ctx.fillRect(0,0,canvas.width,canvas.height); map.forEach((row,y)=>[...row].forEach((cell,x)=>{if(cell==='#'){ctx.fillStyle='#204653';ctx.fillRect(x*TILE+2,y*TILE+2,TILE-4,TILE-4);ctx.strokeStyle='#356270';ctx.strokeRect(x*TILE+5,y*TILE+5,TILE-10,TILE-10);}})); dots.forEach(d=>{ctx.fillStyle=d.power?'#f5c84b':'#d6e4d9';ctx.beginPath();ctx.arc(d.x*TILE+14,d.y*TILE+14,d.power?5:2,0,Math.PI*2);ctx.fill();}); drawPacman();ghosts.forEach(drawGhost); }
function drawPacman(){const px=player.x*TILE+14,py=player.y*TILE+14;ctx.fillStyle='#f5c84b';ctx.beginPath();const angle=Math.atan2(player.dir.y,player.dir.x)||0;const mouth=.25+Math.abs(Math.sin(tick/6))*.18;ctx.moveTo(px,py);ctx.arc(px,py,11,angle+mouth,angle+Math.PI*2-mouth);ctx.closePath();ctx.fill();}
function drawGhost(g){const x=g.x*TILE+14,y=g.y*TILE+14;ctx.fillStyle=g.color;ctx.beginPath();ctx.arc(x,y-2,10,Math.PI,0);ctx.lineTo(x+10,y+10);ctx.lineTo(x+5,y+6);ctx.lineTo(x,y+10);ctx.lineTo(x-5,y+6);ctx.lineTo(x-10,y+10);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x-4,y-3,3,0,7);ctx.arc(x+4,y-3,3,0,7);ctx.fill();ctx.fillStyle='#132129';ctx.beginPath();ctx.arc(x-4+g.dir.x,y-3+g.dir.y,1.5,0,7);ctx.arc(x+4+g.dir.x,y-3+g.dir.y,1.5,0,7);ctx.fill();}
function start(){resetGame();running=true;$('startButton').textContent='PAUSE RUN';$('boardState').textContent='RUN IN PROGRESS';requestAnimationFrame(loop);}
function loop(time){if(!running)return; if(!paused&&time-lastTime>moveInterval()){lastTime=time;tick++;if(player.next.x||player.next.y){if(isOpen(player.x+player.next.x,player.y+player.next.y))player.dir=player.next;}move(player);const hit=dots.findIndex(d=>d.x===player.x&&d.y===player.y);if(hit>=0){score+=dots[hit].power?50:10;dots.splice(hit,1);updateHud();if(dots.length===0){win();return;}}ghosts.forEach((g,i)=>{if(!move(g)){const opts=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}].filter(d=>isOpen(g.x+d.x,g.y+d.y));g.dir=opts[Math.floor(Math.random()*opts.length)]||g.dir;}if(g.x===player.x&&g.y===player.y)collision(i);});draw();}requestAnimationFrame(loop);}
function collision(ghostIndex){if(paused)return;paused=true;lives=Math.max(0,lives-1);questionedGhosts.add(ghostIndex);updateHud();showQuestion();}
function win(){running=false;winCount++;$('endTitle').textContent='Congratulations!';$('endText').textContent='You ate every pellet. Final score: '+String(score).padStart(6,'0')+'. Run '+winCount+' complete. The next run is faster.';$('endScreen').hidden=false;}
function showQuestion(){const item=questions[questionIndex%questions.length];$('questionCount').textContent=`CHECK ${String(questionIndex+1).padStart(2,'0')} / ${String(questions.length).padStart(2,'0')}`;$('questionText').textContent=item.q;$('feedback').textContent='';$('feedback').className='feedback';$('answers').innerHTML='';item.a.forEach((answer,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=answer;b.onclick=()=>answerQuestion(i,item,b);$('answers').appendChild(b);});$('questionModal').hidden=false;}
function answerQuestion(choice,item,button){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(choice===item.correct){button.classList.add('correct');$('feedback').textContent='Correct. The case is back in your hands.';$('feedback').className='feedback good';questionIndex++;setTimeout(()=>{$('questionModal').hidden=true;paused=false;player.x=10;player.y=16;},700);}else{button.classList.add('wrong');$('feedback').textContent='Not quite. Review the details and try again.';$('feedback').className='feedback bad';setTimeout(()=>{document.querySelectorAll('.answer').forEach(b=>b.disabled=false);button.classList.remove('wrong');},650);}}
document.addEventListener('keydown',e=>{const keys={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0}};if(keys[e.key]){e.preventDefault();player.next=keys[e.key];}if(e.key==='Enter'&&!running)start();});document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{if(player)player.next={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[b.dataset.direction];});$('startButton').onclick=()=>{if(!running)start();else{paused=!paused;$('boardState').textContent=paused?'RUN PAUSED':'RUN IN PROGRESS';}};$('restartButton').onclick=()=>{$('endScreen').hidden=true;start();};resetGame();